apiVersion: v1
kind: Service
metadata:
  name: mealie-svc
  namespace: {{ .Release.Namespace | default "mealie" }}
spec:
  selector:
    app: mealie
  ports:
  - protocol: TCP
    name: https
    port: 443
    targetPort: 9000
  - protocol: TCP
    name: http
    port: 80
    targetPort: 9000
  type: {{ .Values.service.type | default "NodePort" }}
